spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 611480782896-fcvt808c51rg93a1td8kith9s5d31ibf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
server:
  port: 8081